version: '3.4'
services: 
  curso-rest:
    image: cfabiogomes/cursorest
    restart: always
    build: ./curso-rest
    working_dir: /curso-rest
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./curso-rest:/curso-rest
      - ~/.m2:/root/.m2
    ports: 
      - "8080:8080"
    command: mvn clean spring-boot:run
    networks: 
      - curso-networks
networks: 
  curso-networks:
    driver: bridge
